#baseurl: /seek

current_seek_version: "1.14.2"
current_docker_tag: "1.14"

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

name: FAIRDOM
url: https://docs.seek4science.org
author: FAIRDOM

theme: just-the-docs

aux_links:
  FAIRDOM: https://fair-dom.org/


back_to_top: true
back_to_top_text: "Back to top"
