# resource general

resource_type_general: A more general term describing the resource.
resource_keywords_label: Key word(s) or key phrase(s) describing the resource.
resource_keywords_label_code: If known, the code of the key word in the used classification/vocabulary.
resource_language: Language of the resource, i.e., the language in which a study is conducted, or the language in which a study document is composed.
resource_version: If existing, the version number of the resource.
resource_web_page: If existing, a link to the web page directly relevant to the resource. (please enter a valid URL starting with http/https)
resource_format: "If applicable, technical format of the resource.
File extension or MIME type can be used, e.g., PDF, XML, MPG or application/pdf, text/xml, video/mpeg."

resource_use_rights_label: License defining the rights to re-use the resource.
resource_use_rights_description: Any additional descriptive information explaining terms and conditions for the (re-)use of the resource.
resource_use_rights_authors_confirmation_1: The authors confirm that they have authority to license the document.
resource_use_rights_authors_confirmation_2: The authors confirm that they have read and understand the terms of the chosen license.
resource_use_rights_authors_confirmation_3: The authors understand that CC licensing is not revocable.
resource_use_rights_support_by_licencing: The authors confirm that NFDI4Health is allowed to licence the document, i.e. to mark the document with the licence information


# role
role: A role, or a contributor, is a person, a group of persons or an institution contributing to the development of the resource.
role_type: Type or role of the contributor.
role_name_type: Type of the name of the conributor.
role_name_organisational: Name of the institution or research group.
role_name_personal_given_name: First name of the person.
role_name_personal_family_name: Last name of the person.
role_name_personal_title: Title of the person.
role_name_identifier: Identifier(s) of the contributor according to various schemes.
role_name_identifier_scheme: Type of the identifier scheme.
role_email: If applicable, email address associated with the contributor.
role_phone: If applicable, phone number associated with the contributor.
role_affiliation_name: Name of the affiliation of the contributor.
role_affiliation_address: address	Address of the affiliation.
role_affiliation_web_page: If available, web page of the affiliation.
role_affiliation_identifier: Identifier(s) of the affiliation.
role_affiliation_identifier_scheme:	Type of the identifier scheme.

# study design general

study_primary_design: Primary design of a study. Select between non-interventional and interventional study design.
study_type_description: If needed, additional descriptive information providing more details about the study type.
study_conditions: Primary health condition(s) or disease(s) studied in the study, or the focus of the study (e.g., medication(s), food(s), therapy(ies), device(s), etc.)
study_conditions_classification: If used, controlled terminology.
study_conditions_classification_code: Code of the term (health condition, disease, or focus of the study) in the used controlled terminology.
study_ethics_commitee_approval: Status of the study approval from the (leading) ethics commitee.


study_status:
study_status_enrolling_by_invitation: Specification whether study participants have been selected from a predetermined population or enrolled by invitation.
study_status_when_intervention: Specification whether study participants receive intervention or have completed it but are still being followed according to the primary objective of the study.
study_status_halted_stage: If the study was stopped prematurely, specification of the stage at what it was halted.
study_status_halted_reason: If the study was stopped prematurely, specification of the reason(s) why it was halted.
study_recruitment_status_register:
study_start_date:
study_end_date: In case of studies with patients or other participants, it is the date when the last participant is examined or receives an intervention, or the date of the last participant’s last visit.
study_region: If applicable, region(s) and/or city(ies) within a country in which the study takes place.
study_centers: Indication, whether a study is conducted at one study site (monocenter study) or at more than one study site (multicenter study).
study_centers_number: Number of study sites involved in the study.
study_subject: Primary unit of operational and/or administrative interest in the study.
study_sampling: Type of the sampling method applied for the selection of study participants.
study_data_source: Sources from which the data are generated or extracted.
study_data_source_description: If needed, additional descriptive information about study data sources (e.g., indication of the data source(s) not listed in the property „Data sources”, or more detailed description of the selected data sources).
study_eligibility_age_min: Minimum age of potential participants eligible to participate in the study provided in years.
study_eligibility_age_min_description: If needed, additional descriptive information about the minimum age of the potential study participants.
study_eligibility_age_max: Maximum age of potential participants eligible to participate in the study provided in years.


study_eligibility_age_max_description: If needed, additional descriptive information about the maximum age of the potential study participants.
study_eligibility_gender: Gender of the potential participants eligible to participate in the study.
study_eligibility_inclusion_criteria: Inclusion criteria for participation in the study.
study_eligibility_exclusion_criteria: Exclusion criteria for participation in the study.
study_population: Additional descriptive information providing more details about study population. Any information important for the given study population can be specified here.



study_target_sample_size: Intended number of observational units for the whole study (e.g., intended number of study participants at all study sites).
study_obtained_sample_size: Obtained number of observational units for the whole study (e.g., obtained number of study participants at all study sites). The value is only available after the end of recruitment.
study_age_min_examined: Minimum age of study participants at the time of examination provided in years.
study_age_min_examined_description: If needed, additional descriptive information about the minimum age of study participants at the time of examination.
study_age_max_examined: Maximum age of study participants at the time of examination provided in years.
study_age_max_examined_description: If needed, additional descriptive information about the maximum age of study participants at the time of examination.
study_hypothesis: Statement of the hypotheses underlying the study.
study_outcome_type: Type of the outcome measure
study_outcome_title: Name of a outcome measure (or for non-interventional studies, name of a specific measurement or observation used to describe patterns of diseases or traits or associations with exposures, risk factors or treatment).

study_outcome_description: Additional descriptive information about the given outcome measure.
study_outcome_time_frame: Description of the time point(s) at which the measurement is assessed for the specific metric used.
study_design_comment: Any additional descriptive information about specific aspects of the study design that cannot be captured by other properties.
study_data_sharing_plan_generally: Indication whether there is a plan to make data collected in the study available. In case of studies with patients or other individuals, this refers to individual participant data (IPD).
study_data_sharing_plan_description: Additional descriptive information providing more details about the data sharing.
study_data_sharing_plan_supporting_information: "Supporting information which will be made available in addition to the study data."
study_data_sharing_plan_time_frame: Indication when the study data and, if applicable, supporting information will become available and for how long.
study_data_sharing_plan_access_criteria: "Indication by what access criteria data will be shared, including:<br>
a) with whom,<br>
b) for what types of analyses, and <br>
c) by what mechanism.<br>"
study_data_sharing_plan_url: If existing, a link to the web page where additional information on data sharing can be found.

# interventional attributes

study_type_interventional: In case of an interventional study, the strategy for assigning interventions to participants.
study_primary_purpose: The main objective of the intervention(s) being evaluated by the study.
study_phase: If applicable, numerical phase of the study.
study_masking: Indication, whether a masking (or blinding) of intervention(s) assignment is implemented (i.e., whether someone is prevented from having knowledge of the interventions assigned to individual participants).
study_masking_roles: If masking is implemented, the party(ies) who are masked.
study_masking_description: If needed, additional descriptive information about masking (e.g., information about other parties who may be masked).
study_allocation: Type of assignment (allocation) of individual participants to an arm.
study_off_label_use: Unapproved (off-label) use of a drug product.
study_arm_group_label: A short name of the arm.
study_arm_group_type: Role of the given arm in the study.
study_arm_group_description: Additional descriptive information about the given arm.
study_intervention_name: A short descriptive name of the intervention.
study_intervention_type: Type of the given intervention.
study_intervention_description: Additional descriptive information about the given intervention.
study_intervention_arm_group_label: Name of the arm associated with the given intervention.

# non_interventional attributes

study_type_non_interventional: In case of a non-interventional study, the primary strategy for participant identification and follow-up.
study_time_perspective: Temporal relationship of observation period to time of participant enrollment.
study_target_follow-up_duration: If applicable, anticipated time period over which each participant is to be followed, provided in years.
study_biospecimen_retention: Indication whether samples of material from study participants are retained in a biorepository.
study_biospecomen_description: Specification all types of biospecimens to be retained (e.g., blood, serum, urine, etc.)
