# resource general

resource_type_general: General type of the resource
resource_keywords_label: Keyword
resource_keywords_label_code: Keyword code
resource_language: Primary language of the resource
resource_version: Version
resource_web_page: Web page
resource_format: Format

resource_use_rights_label: "Use rights: Licence"
resource_use_rights_description: "Use rights: Additional information"
resource_use_rights_authors_confirmation_1: The authors confirm that they have authority to license the document.
resource_use_rights_authors_confirmation_2: The authors confirm that they have read and understand the terms of the chosen license.
resource_use_rights_authors_confirmation_3: The authors understand that CC licensing is not revocable.
resource_use_rights_support_by_licencing: The authors confirm that NFDI4Health is allowed to licence the document, i.e. to mark the document with the licence information.


# roles

role: Contributors
role_type: Role
role_name_type: Type of the name
role_name_organisational: Name
role_name_personal_given_name: First name
role_name_personal_family_name:	Last name
role_name_personal_title: Title
role_name_identifier: ID
role_name_identifier_scheme: Scheme
role_email: Email
role_phone: Phone
role_affiliation_name: Affiliation
role_affiliation_address: Affiliation address
role_affiliation_web_page: Affiliation web page
role_affiliation_identifier: Affiliation ID
role_affiliation_identifier_scheme: Scheme

# study design general

study_primary_design: Primary design of the study.
study_type_description: Additional information on study design.
study_conditions: Primary disease or health condition(s) studied, or fokus of the study.
study_conditions_classification: Controlled terminology name. It is mandatory if the study conditions are given.
study_conditions_classification_code: Code of the term in the controlled terminology (IRI).
study_ethics_commitee_approval: Approval from the ethics commitee.
study_status: Overall status for the study.
study_status_enrolling_by_invitation: Are participants enrolled by invitation?
study_status_when_intervention: Do participants receive an intervention?
study_status_halted_stage: At what stage the study was halted?
study_status_halted_reason: Reason why study was halted.
study_recruitment_status_register: Overall recruitment status for the study.
study_start_date:  Start date of data collection for the study.
study_end_date: End date of data collection for the study.
study_region: Region(s) and/or cities within a country, in which the study takes place.
study_centers: Is the study conducted at one study or more than one study sites?
study_centers_number: Number of study sites.
study_subject: Primary unit of interest in the study.
study_sampling: Applied sampling method.
study_data_source: Sources from which the data are generated or extracted.
study_data_source_description: Additional information on study data sources.
study_eligibility_age_min: Minimum age of participants in years.
study_eligibility_age_min_description: Additional information about the minimum age of participants.
study_eligibility_age_max: Maximum age of participants in years.
study_eligibility_age_max_description: Additional information about the maximum age of participants.
study_eligibility_gender: Gender of participants.
study_eligibility_inclusion_criteria: Inclusion criteria for study.
study_eligibility_exclusion_criteria: Exclusion criteria for study.
study_population: Description of study population.
study_target_sample_size: Intended number of study observational units.
study_obtained_sample_size: Obtained number of study observational units.
study_age_min_examined: Minimum age of participants in years.
study_age_min_examined_description: Additional information about the minimum age of participants.
study_age_max_examined: Maximum age of participants in years.
study_age_max_examined_description: Additional information about the maximum age of participants.
study_hypothesis: Hypotheses underlying the study.
study_outcome_type: Type of the outcome measure.
study_outcome_title: Name of the outcome measure.
study_outcome_description: Additional information about the outcome measure.
study_outcome_time_frame: Time frame of assessment specific to the outcome measure.
study_design_comment: Additional information on the study design.
study_data_sharing_plan_generally: Plan to share the data?
study_data_sharing_plan_description: Additional information on data sharing statement.
study_data_sharing_plan_supporting_information: Supporting information available in addition to the study data.
study_data_sharing_plan_time_frame: Data availability time frame.
study_data_sharing_plan_access_criteria: Criteria for the access to the study data.
study_data_sharing_plan_url: Web page with additional information on data sharing. (please enter a valid URL starting with http/https)

# interventional attributes

study_type_interventional: Specific type of the study.
study_primary_purpose: The main purpose of the intervention(s).
study_phase: Numerical phase of the study.
study_masking: Is masking of intervention(s) assignment implemented?
study_masking_roles: Party(ies) who are masked.
study_masking_description: Additional information about masking.
study_allocation: Type of allocation of individual participants to an arm.
study_off_label_use: Off-label use of a drug product.
study_arm_group_label: Name of the arm.
study_arm_group_type: Role of the arm in the study. It is mandatory if study arm group label is given.
study_arm_group_description: Additional information on the arm.
study_intervention_name: Name of the intervention.
study_intervention_type: Type of the intervention.
study_intervention_description: Additional information on the intervention.
study_intervention_arm_group_label: Arm associated with the intervention.

# non_interventional attributes

study_type_non_interventional: Specific type of the study.
study_time_perspective: Relationship of observation period to time of enrollment.
study_target_follow-up_duration: Target follow-up duration.
study_biospecimen_retention: Which biosamples are retained?
study_biospecomen_description: Biosamples to be retained.
