# resource general

resource_type_general: General type of the resource
resource_keywords_label: Keyword
resource_keywords_label_code: Keyword code
resource_language: Primary language of the resource
resource_version: Version
resource_web_page: Web page
resource_format: Format

resource_use_rights_label: "Use rights: Licence"
resource_use_rights_description: "Use rights: Additional information"
resource_use_rights_authors_confirmation_1: The authors confirm that they have authority to license the document.
resource_use_rights_authors_confirmation_2: The authors confirm that they have read and understand the terms of the chosen license.
resource_use_rights_authors_confirmation_3: The authors understand that CC licensing is not revocable.
resource_use_rights_support_by_licencing: The authors confirm that NFDI4Health is allowed to licence the document, i.e. to mark the document with the licence information.


# roles

role: Contributors
role_type: Role
role_name_type: Type of the name
role_name_organisational: Name
role_name_personal_given_name: First name
role_name_personal_family_name:	Last name
role_name_personal_title: Title
role_name_identifier: ID
role_name_identifier_scheme: Scheme
role_email: Email
role_phone: Phone
role_affiliation_name: Affiliation
role_affiliation_address: Affiliation address
role_affiliation_web_page: Affiliation web page
role_affiliation_identifier: Affiliation ID
role_affiliation_identifier_scheme: Scheme

# study design general

study_primary_design: Study primary design
study_type_description: Description of study type
study_conditions: Health conditions or diseases studied in the study
study_conditions_classification: Terminology
study_conditions_classification_code: Code
study_ethics_commitee_approval: Status of the ethics commitee approval


study_status: Overall status of the study
study_status_enrolling_by_invitation: Are participants enrolled by invitation?
study_status_when_intervention: Do participants receive an intervention?
study_status_halted_stage: At what stage the study was halted?
study_status_halted_reason: Reason why study was halted.
study_recruitment_status_register: Overall recruitment status for the study.
study_start_date:  Start date of data collection for the study
study_end_date: End date of data collection for the study
study_country: Countries where the study takes place
study_region: Regions and/or cities where the study takes place
study_centers: Is the study conducted at one study site or more than one study sites?
study_centers_number: Number of study sites.
study_subject: Primary unit of interest in the study

study_sampling: Applied sampling method.
study_data_source: Data sources

study_data_source_description: Additional information about data sources
study_eligibility_age_min: "Eligibility criteria: Minimum age"
study_eligibility_age_min_description: "Eligibility criteria: Additional information about the minimum age"
study_eligibility_age_max: "Eligibility criteria: Maximum age"
study_eligibility_age_max_description: "Eligibility criteria: Additional information about the maximum age"
study_eligibility_gender: "Eligibility criteria: Gender"
study_eligibility_inclusion_criteria: "Eligibility criteria: Inclusion criteria."
study_eligibility_exclusion_criteria: "Eligibility criteria: Exclusion criteria"
study_population: Description of study population
study_target_sample_size: Target sample size
study_obtained_sample_size: Obtained sample size
study_age_min_examined: Actual minimum age of participants
study_age_min_examined_description: Additional information about the actual minimum age
study_age_max_examined: Actual maximum age of participants
study_age_max_examined_description: Additional information about the actual maximum age




study_hypothesis: Hypotheses underlying the study

study_outcomes: Study outcomes
study_outcome_type: Type of the outcome measure
study_outcome_title: Name of the outcome measure
study_outcome_description: Description of the outcome measure
study_outcome_time_frame: Time frame of the assessment specific to the outcome measure

study_design_comment: Additional information on the study design


study_data_sharing_plan_generally: Plan to share the data?
study_data_sharing_plan_description: Additional information on data sharing
study_data_sharing_plan_supporting_information: Supporting information available in addition to the study data
study_data_sharing_plan_time_frame: Data availability time frame
study_data_sharing_plan_access_criteria: Criteria for the access to the study data
study_data_sharing_plan_url: Web page with additional information on data sharing

# interventional attributes

study_type_interventional: Study type
study_primary_purpose: The main purpose of the intervention(s)
study_phase: Numerical phase of the study
study_masking: Is masking of intervention(s) assignment implemented?
study_masking_roles: Masked party(ies)
study_masking_description: Additional information about masking
study_allocation: Type of allocation of participants to an arm
study_off_label_use: Off-label use of a drug product

#interventional_study_design_arms
interventional_study_design_arms: Study arms
study_arm_group_label: Name of the arm
study_arm_group_type: Role of the arm
study_arm_group_description: Additional information about the arm

#interventional_study_design_interventions
interventional_study_design_interventions: Study design interventions
study_intervention_name: Name of the intervention
study_intervention_type: Type of the intervention.
study_intervention_description: Additional information about the intervention
study_intervention_arm_group_label: Associated arm

# non_interventional attributes
study_type_non_interventional: Study type
study_time_perspective: "Study type: Time perspective"
study_target_follow-up_duration: Target follow-up duration
study_biospecimen_retention: Which biosamples are retained?
study_biospecomen_description: Additional information about biosamples to be retained
