study_resource_type:
  id: 1
  title: Study
  key: study

substudy_resource_type:
  id: 2
  title: Substudy/Data collection event
  key: substudy

dataset_resource_type:
  id: 3
  title: Dataset
  key: dataset

study_protocol_resource_type:
  id: 4
  title: Study protocol
  key: study_protocol


protocol_amendment_resource_type:
  id: 5
  title: Protocol amendment
  key: protocol_amendment

data_dictionary_resource_type:
  id: 6
  title: Data dictionary
  key: data_dictionary

informed_consentForm_resource_type:
  id: 7
  title: Informed consent form
  key: informed_consent_form

patient_information_sheet_resource_type:
  id: 8
  title: Patient information sheet
  key: patient_information_sheet

sop_resource_type:
  id: 9
  title: Manual of operations (SOPs)
  key: sop

statistical_analysis_plan_resource_type:
  id: 10
  title: Statistical analysis plan
  key: statistical_analysis_plan

data_management_plan_resource_type:
  id: 11
  title: Data management plan
  key: data_management_plan

case_report_form_resource_type:
  id: 12
  title: Case report form
  key: case_report_form

code_book_resource_type:
  id: 13
  title: Code book
  key: code_book


questionnaire_resource_type:
  id: 14
  title: Questionnaire
  key: questionnaire

interview_scheme_and_theme_resource_type:
  id: 15
  title: Interview scheme and themes
  key: interview_scheme_and_theme

observation_guide_resource_type:
  id: 16
  title: Observation guide
  key: observation_guide

discussion_guide_resource_type:
  id: 17
  title: Discussion guide
  key: discussion_guide

participant_tasks_resource_type:
  id: 18
  title: Participant tasks
  key: participant_tasks


other_data_collection_instrument_resource_type:
  id: 19
  title: Other data collection instrument
  key: other_data_collection_instrument

other_study_document_resource_type:
  id: 20
  title: Other study document
  key: other_study_document

other_non_study_resource_type:
  id: 21
  title: Other resource
  key: other_non_study