study_resource_type:
  id: 1
  title: Study
  key: study

substudy_resource_type:
  id: 2
  title: Substudy/Data collection event
  key: substudy

dataset_resource_type:
  id: 3
  title: Dataset
  key: dataset

study_protocol_resource_type:
  id: 4
  title: Study Protocol
  key: study_protocol


protocol_amendment_resource_type:
  id: 5
  title: Protocol Amendment
  key: protocol_amendment

data_dictionary_resource_type:
  id: 6
  title: Data Dictionary
  key: data_dictionary

informed_consentForm_resource_type:
  id: 7
  title: Informed Consent Form
  key: informed_consentForm

patient_information_sheet_resource_type:
  id: 8
  title: Patient Information Sheet
  key: patient_information_sheet

sop_resource_type:
  id: 9
  title: Manual of Operations (SOPs)
  key: sop

sstatistical_analysis_plan_resource_type:
  id: 10
  title: Statistical Analysis Plan
  key: sstatistical_analysis_plan

data_management_plan_resource_type:
  id: 11
  title: Data Management Plan
  key: data_management_plan

case_report_form_resource_type:
  id: 12
  title: Case Report Form
  key: case_report_form

code_book_resource_type:
  id: 13
  title: Code Book
  key: code_book


questionnaire_resource_type:
  id: 14
  title: Questionnaire
  key: questionnaire

interview_scheme_and_theme_resource_type:
  id: 15
  title: Interview Scheme and Themes
  key: interview_scheme_and_theme

observation_guide_resource_type:
  id: 16
  title: Observation Guide
  key: observation_guide

discussion_guide_resource_type:
  id: 17
  title: Discussion Guide
  key: discussion_guide

participant_tasks_resource_type:
  id: 18
  title: Participant Tasks
  key: participant_tasks


other_data_collection_instrument_resource_type:
  id: 19
  title: Other Data Collection Instrument
  key: other_data_collection_instrument

other_study_document_resource_type:
  id: 20
  title: Other Study Document
  key: other_study_document

other_resource_type:
  id: 21
  title: Other
  key: other

