investigation_checksum: https://docs.seek4science.org/tech/investigation-checksum.html
roles: https://docs.seek4science.org/help/user-guide/roles.html
programme_self_management: https://about.workflowhub.eu/docs/joining-a-team/#create-your-own-team
get_started: https://about.workflowhub.eu/docs/getting-started/
get_involved: https://about.workflowhub.eu/
registering: https://about.workflowhub.eu/docs/how-to-register/
join_project: https://about.workflowhub.eu/docs/joining-a-team/
credits: https://docs.seek4science.org/credits
admin_project_members: https://docs.seek4science.org/help/user-guide/administer-project-members.html
isa_overview: https://docs.seek4science.org/help/user-guide/isa-overview.html
null_license: https://choosealicense.com/no-permission/
data_file_wizard: https://docs.seek4science.org/help/user-guide/data-file-upload-wizard.html
dashboard: https://docs.seek4science.org/help/user-guide/project-dashboard.html
report_bugs_and_features: https://docs.seek4science.org/tech/reporting-bugs-and-features.html
Collection: https://docs.seek4science.org/help/user-guide/collections.html
Institution: https://about.workflowhub.eu/docs/what-is-a-team/#what-is-an-organization
#Person: https://docs.seek4science.org/help/user-guide/registering.html
Programme: https://about.workflowhub.eu/docs/what-is-a-team/#what-is-a-space
Project: https://about.workflowhub.eu/docs/what-is-a-team/#what-is-a-team
Investigation: https://docs.seek4science.org/help/isa-guide.html
Study: https://docs.seek4science.org/help/isa-guide.html
Assay: https://docs.seek4science.org/help/isa-guide.html
DataFile: https://docs.seek4science.org/help/user-guide/general-attributes.html#data-files
Sop: https://docs.seek4science.org/help/user-guide/general-attributes.html#sops
Publication: https://docs.seek4science.org/help/user-guide/general-attributes.html#publications
Sample: https://docs.seek4science.org/help/user-guide/samples.html
SampleType: https://docs.seek4science.org/help/user-guide/create-sample-type.html
Organism: https://docs.seek4science.org/help/user-guide/general-attributes.html#organisms
Model: https://docs.seek4science.org/help/user-guide/adding-assets.html
Document: https://docs.seek4science.org/help/user-guide/adding-assets.html
Presentation: https://docs.seek4science.org/help/user-guide/adding-assets.html
Event: https://docs.seek4science.org/help/user-guide/general-attributes.html#events
clipboard_api_mozilla: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
